In [1]:
import pandas as pd
import numpy as np
import random

# Grid

In [2]:
grid = np.zeros((5,5))
grid

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Pieces

## Player 1

In [3]:
p1_4x1 = np.array([[1,1,1,1]])
p1_4x1

array([[1, 1, 1, 1]])

In [4]:
p1_3x1 = np.array([[1,1,1]])
p1_3x1

array([[1, 1, 1]])

In [5]:
p1_2x1 = np.array([[1,1]])
p1_2x1

array([[1, 1]])

In [6]:
p1_L = np.array([[1,0,0], [1,1,1]])
p1_L

array([[1, 0, 0],
       [1, 1, 1]])

In [7]:
p1_square = np.array([[1,1], [1,1]])
p1_square

array([[1, 1],
       [1, 1]])

In [8]:
p1_corner = np.array([[1,0], [1,1]])
p1_corner

array([[1, 0],
       [1, 1]])

In [9]:
p1_pipe = np.array([[0,1,0], [1,1,1]])
p1_pipe

array([[0, 1, 0],
       [1, 1, 1]])

In [10]:
p1_bend = np.array([[0,1,1], [1,1,0]])
p1_bend

array([[0, 1, 1],
       [1, 1, 0]])

In [43]:
p1_pieces = [
    p1_4x1,
    p1_3x1,
    p1_2x1,
    p1_L,
    p1_square,
    p1_corner,
    p1_pipe,
    p1_bend
]

## Player 2

In [44]:
p2_4x1 = np.array([[2,2,2,2]])
p2_3x1 = np.array([[2,2,2]])
p2_2x1 = np.array([[2,2]])
p2_L = np.array([[2,0,0], [2,2,2]])
p2_square = np.array([[2,2], [2,2]])
p2_corner = np.array([[2,0], [2,2]])
p2_pipe = np.array([[0,2,0], [2,2,2]])
p2_bend = np.array([[0,2,2], [2,2,0]])

p2_pieces = [
    p2_4x1,
    p2_3x1,
    p2_2x1,
    p2_L,
    p2_square,
    p2_corner,
    p2_pipe,
    p2_bend
]

# Play

In [47]:
def orient(p):
    k = random.randint(1,4)
    return np.rot90(p, k=k)


def fill_out(p):
    rows, cols = p.shape

    row_max_start = 5-rows
    col_max_start = 5-cols

    row_start = random.randint(0, row_max_start)
    col_start = random.randint(0, col_max_start)

    row_top_pad = row_start
    row_bottom_pad = row_max_start - row_start
    col_left_pad = col_start
    col_right_pad = col_max_start - col_start

    return np.pad(p, ((row_top_pad,row_bottom_pad), (col_left_pad,col_right_pad)))


def play_move(piece_list, grid):
    
    attempt_counter = 0
    
    while attempt_counter < 1000:
    
        # Randomly choose a piece
        piece_i = random.randint(0, len(piece_list)-1)
        piece = piece_list[piece_i]

        # Randomly rotate piece and place it's location
        layer = fill_out(orient(piece))

        # Check if it is a legal move
        # Are any spots already taken?
        if (grid*layer).max() == 0:
            grid+=layer
            del piece_list[piece_i]
            return grid, piece_list

        attempt_counter+=1
        if attempt_counter==1000:
            return grid, piece_list

In [50]:
i=0
grid = np.zeros((5,5))
p1_pieces = [
    p1_4x1, p1_3x1, p1_2x1, p1_L, p1_square, p1_corner, p1_pipe, p1_bend
]
p2_pieces = [
    p2_4x1, p2_3x1, p2_2x1, p2_L, p2_square, p2_corner, p2_pipe, p2_bend
]

while i<=20:
    # Figure out whose turn it is and get their available pieces
    piece_list = p1_pieces if i%2 == 0 else p2_pieces
    if len(piece_list) > 0:
        grid, piece_list = play_move(piece_list, grid)
        
    print(grid, '\n')
        
    i+=1

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 0. 2.]] 

[[0. 0. 1. 0. 0.]
 [1. 0. 1. 1. 2.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 0. 2.]] 

[[0. 0. 1. 0. 0.]
 [1. 0. 1. 1. 2.]
 [1. 0. 0. 0. 2.]
 [1. 0. 2. 2. 2.]
 [1. 0. 2. 2. 2.]] 

[[0. 0. 1. 0. 0.]
 [1. 0. 1. 1. 2.]
 [1. 1. 1. 0. 2.]
 [1. 1. 2. 2. 2.]
 [1. 1. 2. 2. 2.]] 

[[0. 2. 1. 0. 0.]
 [1. 2. 1. 1. 2.]
 [1. 1. 1. 0. 2.]
 [1. 1. 2. 2. 2.]
 [1. 1. 2. 2. 2.]] 

[[0. 2. 1. 1. 1.]
 [1. 2. 1. 1. 2.]
 [1. 1. 1. 0. 2.]
 [1. 1. 2. 2. 2.]
 [1. 1. 2. 2. 2.]] 

[[0. 2. 1. 1. 1.]
 [1. 2. 1. 1. 2.]
 [1. 1. 1. 0. 2.]
 [1. 1. 2. 2. 2.]
 [1. 1. 2. 2. 2.]] 

[[0. 2. 1. 1. 1.]
 [1. 2. 1. 1. 2.]
 [1. 1. 1. 0. 2.]
 [1. 1. 2. 2. 2.]
 [1. 1. 2. 2. 2.]] 

[[0. 2. 1. 1. 1.]
 [1. 2. 1. 1. 2.]
 [1. 1. 1. 0. 2.]
 [1. 1. 2. 2. 2.]
 [1. 1. 2. 2. 2.]] 

[[0. 2. 1. 1. 1.]
 [1. 2. 1. 1. 2.]
 [1. 1. 1. 0. 2.]
 [1. 1. 2. 2. 2.

In [51]:
grid

array([[0., 2., 1., 1., 1.],
       [1., 2., 1., 1., 2.],
       [1., 1., 1., 0., 2.],
       [1., 1., 2., 2., 2.],
       [1., 1., 2., 2., 2.]])

In [31]:
i=0
grid = np.zeros((5,5))
possible_moves = []

while i<=5:
    # Figure out whose turn it is and get their available pieces
    piece_list = p1_pieces if i%2 == 0 else p2_pieces
    player = 1 if i%2 == 0 else 2
    
    # Randomly choose a piece
    piece_i = random.randint(0, len(piece_list)-1)
    piece = piece_list[piece_i]
    
    #print(piece)
    
    # Randomly rotate piece and place it's location
    layer = fill_out(orient(piece))
    
    #print(layer, '\n')
    
    # Check if it is a legal move
    # Are any spots already taken?
    if (grid*layer).max() == 0:
        grid+=layer
        
    print(grid, '\n')
    
    i+=1

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]] 

[[0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [2. 2. 1. 0. 0.]
 [2. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]] 

[[0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [2. 2. 1. 0. 0.]
 [2. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]] 

[[0. 0. 0. 0. 0.]
 [2. 0. 0. 2. 2.]
 [2. 2. 1. 2. 2.]
 [2. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]] 

[[0. 0. 0. 0. 0.]
 [2. 0. 0. 2. 2.]
 [2. 2. 1. 2. 2.]
 [2. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]] 

[[0. 0. 0. 0. 0.]
 [2. 0. 0. 2. 2.]
 [2. 2. 1. 2. 2.]
 [2. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]] 



In [27]:
grid

array([[0., 0., 1., 1., 1.],
       [0., 0., 0., 2., 2.],
       [0., 0., 1., 2., 2.],
       [0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
grid = np.array([[0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]])
grid

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [71]:
p = np.array([[0, 1, 0, 0, 0], [0, 1, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]])
p

array([[0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [75]:
res = grid+p
res

array([[0, 1, 0, 0, 0],
       [0, 1, 2, 0, 0],
       [0, 0, 2, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [76]:
res.max()

2

In [83]:
set(list(res.flatten()))

{0, 1, 2}

In [84]:
res

array([[0, 1, 0, 0, 0],
       [0, 1, 2, 0, 0],
       [0, 0, 2, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
{0,1,2,3}.intersection({2})

{2}

In [172]:
def orient(p):
    k = random.randint(1,4)
    return np.rot90(p, k=k)


def fill_out(p):
    rows, cols = p.shape

    row_max_start = 5-rows
    col_max_start = 5-cols

    row_start = random.randint(0, row_max_start)
    col_start = random.randint(0, col_max_start)

    row_top_pad = row_start
    row_bottom_pad = row_max_start - row_start
    col_left_pad = col_start
    col_right_pad = col_max_start - col_start

    return np.pad(p, ((row_top_pad,row_bottom_pad), (col_left_pad,col_right_pad)))

In [181]:
fill_out(orient(p1_L))

array([[0, 0, 1, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [162]:
orient(p1_L)

array([[0, 1],
       [0, 1],
       [1, 1]])

In [142]:
rows, cols = p1_L.shape

row_max_start = 5-rows
col_max_start = 5-cols

row_start = random.randint(0, row_max_start)
col_start = random.randint(0, col_max_start)

row_top_pad = row_start
row_bottom_pad = row_max_start - row_start
col_left_pad = col_start
col_right_pad = col_max_start - col_start

np.pad(p1_L, ((row_top_pad,row_bottom_pad), (col_left_pad,col_right_pad)))

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0]])

# Moves

In [12]:
np.rot90(p2, k=2)

array([[1, 1, 1],
       [0, 0, 1]])